# Generated by Django 5.0.2 on 2025-07-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('propert_title', models.CharField(max_length=200)),
                ('property_location', models.CharField(max_length=255)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_type', models.CharField(choices=[('select', 'select'), ('House', 'House'), ('Apartment', 'Apartment'), ('Condo', 'Condo'), ('townhouse', 'Townhouse'), ('Other', 'Other')], max_length=100)),
                ('no_of_bedrooms', models.IntegerField(blank=True, null=True)),
                ('no_of_bathrooms', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('select', 'select'), ('House renovation', 'House Renovation'), ('Interior painting', 'Interior Painting'), ('Exterior painting', 'Exterior Painting'), ('Kitchen renovation', 'Kitchen Renovation'), ('Bathroom renovation', 'Bathroom Renovation'), ('Other', 'Other')], max_length=100)),
                ('Service_urgency', models.CharField(choices=[('select', 'select'), ('2 Weeks', '2 Weeks'), ('1 Month', '1 Month'), ('3 Months', '3 Months')], max_length=100)),
                ('preffered_date', models.DateField()),
                ('description', models.TextField()),
                ('imag', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
