# Generated by Django 5.0.2 on 2025-07-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactss', '0002_sell_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='area',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='property_price',
            field=models.CharField(max_length=20),
        ),
    ]
