# Generated by Django 5.0.2 on 2025-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_feature_property_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='for_type',
            field=models.CharField(choices=[('select', 'Select'), ('sale', 'For Sale'), ('rent', 'For Rent')], default='select', max_length=50),
        ),
    ]
