# Generated by Django 5.0.2 on 2025-07-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_for_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('proj_type', models.CharField(choices=[('Commercial', 'Commercial'), ('Residential', 'Residential'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Other', 'Other')], default='Commercial', max_length=50)),
                ('client_name', models.CharField(max_length=255)),
                ('proj_area', models.CharField(max_length=100)),
                ('proj_duration', models.CharField(max_length=100)),
                ('professionals', models.IntegerField(default=0)),
                ('proj_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('proj_status', models.CharField(choices=[('Planning', 'Planning'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Planning', max_length=50)),
                ('image_urls', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenges', models.ManyToManyField(blank=True, related_name='projects', to='properties.projectchallenge')),
                ('features', models.ManyToManyField(blank=True, related_name='projects', to='properties.projectfeature')),
                ('outcomes', models.ManyToManyField(blank=True, related_name='projects', to='properties.projectoutcome')),
            ],
        ),
    ]
