# Generated by Django 5.0.2 on 2025-07-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_projectchallenge_projectfeature_projectoutcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.RemoveField(
            model_name='project',
            name='outcomes',
        ),
        migrations.DeleteModel(
            name='ProjectChallenge',
        ),
        migrations.DeleteModel(
            name='ProjectFeature',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectOutcome',
        ),
    ]
