# Generated by Django 5.0.2 on 2025-07-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_description', models.TextField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('proj_area', models.CharField(max_length=200)),
                ('proj_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Mixed Use', 'Mixed Use'), ('Other', 'Other')], max_length=200)),
                ('proj_status', models.CharField(choices=[('Planning', 'Planning'), ('Under Construction', 'Under Construction'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], max_length=200)),
                ('proj_duration', models.CharField(max_length=200)),
                ('professionals', models.IntegerField()),
                ('proj_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('challenges', models.ManyToManyField(blank=True, to='projects.challenges')),
                ('features', models.ManyToManyField(blank=True, to='projects.features')),
            ],
        ),
    ]
