# Generated by Django 5.0.2 on 2025-07-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_features_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(blank=True, to='projects.features'),
        ),
    ]
