# Generated by Django 5.0.2 on 2025-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_features_project_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.DeleteModel(
            name='Challenges',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
