# Generated by Django 5.0.2 on 2025-07-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_challenges_remove_project_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
