# Generated by Django 5.0.2 on 2025-07-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_challenges_alter_project_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='Challenges',
            field=models.ManyToManyField(blank=True, to='projects.challenge'),
        ),
        migrations.AddField(
            model_name='project',
            name='Features',
            field=models.ManyToManyField(blank=True, to='projects.feature'),
        ),
    ]
