# Generated by Django 5.0.2 on 2025-07-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_challenge_feature_remove_project_challenges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Challenges',
            new_name='challenges',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Features',
            new_name='features',
        ),
    ]
