# Generated by Django 5.0.2 on 2025-07-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_challenges_project_challenges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='challenges',
            new_name='challengess',
        ),
    ]
