# Generated by Django 5.0.2 on 2025-07-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_challenges_project_challengess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='challengess',
            new_name='Challengess',
        ),
    ]
