# Generated by Django 5.0.2 on 2025-07-21 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_challengess_project_challenges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenges_projects', to='projects.challenge'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features_projects', to='projects.feature'),
        ),
    ]
