# Generated by Django 5.0.2 on 2025-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_project_challenges_remove_project_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='features',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.ManyToManyField(blank=True, related_name='challenges_projects', to='projects.challenge'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features_projects', to='projects.feature'),
        ),
    ]
