# Generated by Django 5.0.2 on 2025-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_outcomes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
