# Generated by Django 5.0.2 on 2025-07-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_project_completed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomes',
            name='project',
        ),
    ]
