# Generated by Django 5.0.2 on 2025-07-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_outcomes_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='outcomes_projects', to='projects.outcomes'),
        ),
    ]
