# Generated by Django 5.0.2 on 2025-07-24 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_outcomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomes',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_set', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.outcomes'),
        ),
    ]
