# Generated by Django 5.0.2 on 2025-07-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_outcomes_project_alter_project_outcomes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='outcomes',
            new_name='Outcome',
        ),
    ]
