# Generated by Django 5.0.2 on 2025-07-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_rename_outcomes_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='project',
        ),
        migrations.AlterField(
            model_name='outcome',
            name='outcome',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
